Notepad contains clues and images
gabelepoudre/406-mystery-deckbuilder pull request #75
Opened 2023-03-27 22:12 UTC by eimearcurrie

# Pull Request

## Describe your changes

Added clues to display after encounter is won, added sprite images for NPCs and zones, and zone clues

## Suggested reviewers (also add these to "reviewers" on the right menu)

Any programmer

## Quality Assurance checklist (for code PRs)
- [X] I have manually tested my code and fixed all bugs I am aware of
- [X] I have manually reviewed my code
- [X] I have adhered to the [Style Guide](style.md) within reason
- [X] I have adhered to the [Practices Guide](practices.md) and commented all code

## Additional Notes

Still a work in progress but should be sufficient for play testing. Some NPC clues haven't been written yet but can be filled in at a later point.

2023-03-27 22:43 UTC, gabelepoudre requested changes
Hey! Looks good in your test scene, but hasn't been implemented into the World UI prefab and so it breaks on normal gameplay. You get a UnassignedReferenceException

2023-03-28 04:34 UTC, g-stru requested changes
Everything looks great, except the Pause and Glub buttons in the WorldUI seemed to have stopped working, I dont think they're pointing to anything

2023-03-28 05:06 UTC, g-stru approved these changes
Works now!

2023-03-28 05:07 UTC, g-stru approved these changes

2023-03-28 05:09 UTC, g-stru approved these changes

2023-03-29 04:28 UTC, gabelepoudre approved these changes

2023-03-29 22:53 UTC, merged